---
- name: compute related workarounds
  hosts: compute
  become: yes
  any_errors_fatal: yes
  gather_facts: no
  tasks:
      - name: "w/a for 1477720"
        shell: |
           setenforce 0
        tags: skip_ansible_lint
