---
- name: Check if there any remaining updates on {{ node_name }}
  become: true
  command: yum check-update
  register: yum_update
  failed_when: false
  delegate_to: "{{ node_name }}"

- block:
    - name: list not-updated packages
      debug:
          msg: "{{ yum_update.stdout }}"

    - fail:
          msg: "There are remaining packages to be updated on {{ hostvars[node_name].ansible_fqdn }} or yum didn't run successfully"
  when: yum_update.rc in [1, 100]
